config/routes.rb
Rails.application.routes.draw do
  #create a full CRUD path for resources
  get "/", to: "pages#home", as: "root"
  resources :listings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
    has_many :listings
    #A breed can have many listings,
    #there can be many anaconda listings for example.

    #enum --> a set of named key value pairs
    
end

app/models/listing.rb
class Listing < ApplicationRecord
  #using the foreign key "breed_id"
  belongs_to :breed
  
  #make a list of named key value pairs 
  # in an enum --> useful for when values
  # must be something in particular
  enum sex: { female:0, male:1 }

  #when we pass through 'female' in the listing
  # it saves

  #validates makes sure that data is entered
  #sets required field with the rule of (presence).
  #there are many different built in validation rules
  validates :title, :breed_id, :sex, :price, :deposit, :date_of_birth, presence: true
  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    #before action runs before anything else,
    #and it will look for a method called set_listing
    # BUT only run on these 4 methods using only keyword
    before_action :set_listing, only: [:show, :edit, :update, :destroy]
    before_action :set_breeds_and_sexes, only: [:new, :edit]
    def create
        #creates new listing

        #we want to whitelist because we know which value
        # to accept.

        #.create creates a new record from the method
        # which passes through the whitelisted values
        @listing = Listing.create(listing_params)

        #if there are errors, show errors (using listing var), if not, redirect to the listings page
        if @listing.errors.any?
            set_breeds_and_sexes
            render "new"
        else
            redirect_to listings_path
        end
        
        # byebug
    end
    
    def update
        #updates the current listing
    end

    def index
        #shows all listings

        #Make an instance variable that has all 
        #listings from db

        @listings = Listing.all
    
    end

    def edit
        #shows the edit form
    end

    def destroy
        #deletes current listings

    end

    def new 
        #shows form for creating a new listing
        @listing = Listing.new
    end

    def show
        #view a single listing
    end

    #private makes set_listing only accessible inside the object
    
    private 

    def set_breeds_and_sexes
        @breeds = Breed.all
        @sexes = Listing.sexes.keys
    end

    def set_listing
        #access the params hash, and pick out 
        #a particular id. Assign this to a 
        # variable 'id'
        #then use this id to create a var of the
        # particular listing

        id = params[:id]
        @listing = Listing.find(id)
    end

    def listing_params
        params.require(:listing).permit(:title, :description, :breed_id, :sex, :price, :deposit, :date_of_birth)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        render plain: "homepage"
        #todo - put in view here for homepage
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeglessPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%if listing.errors.any?%>

    <%listing.errors.full_messages.each do |error|%>
        <p><%=error %></p>
    <%end%>
<%end%>
<!-- Create a new instance of Listing as the model for the form -->
<%= form_with(model: listing, local: true) do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :price %>
        <%= form.number_field :price, min: 0 %>
    </div>
    <div>
        <%= form.label :deposit %>
        <%= form.number_field :deposit, min: 0 %>
    </div>
    <div>
        <%= form.label :city %>
        <%= form.text_field :city %>
    </div>
    <div>
        <%= form.label :state %>
        <%= form.text_field :state %>
    </div>
    <div>
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth %>
    </div>
    <div>
        <%= form.label :diet %>
        <%= form.text_field :diet %>
    </div>
    <div>
    <%= form.label :breed_id %>
    <%= form.select(:breed_id, breeds.map{|b| [b.name, b.id]}) %>
    </div>
    <%sexes.each do |option| %>
        <div>
        <%= form.radio_button :sex, option%>
        <%= form.label "sex_#{option}.to_sym", option %> 
        </div>
    <%end%>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/listings/edit.html.erb
<h1> Edit Listing</h1>

<%= render "form", listing: @listing, breeds: @breeds, sexes: @sexes %>

app/views/listings/index.html.erb
<h1> Snake listings <h1>

<%@listings.each do |listing|%>
    <div class = "card">
    <p><%=listing.title%></p>
    <p><%=listing.description%></p>
    <p><%=listing.breed.name%></p>
    <!-- Add a link to edit this particular listing using listing.id as arg-->
    <%= link_to "edit", edit_listing_path(listing.id) %>

    </div>
<%end%>

app/views/listings/new.html.erb
<h1> New Listing </h1>
<%= render "form", listing: @listing, breeds: @breeds, sexes: @sexes %>